CC = gcc
CFLAGS = -mno-cygwin -O2 -g -ggdb -pipe
LIBS = -lcrypto 
LDFLAGS = $(CFLAGS)

SOURCES = md5sum.c md5.c
OBJECTS = ${SOURCES:.c=.o}

all: md5sum.exe

clean:
	-rm -f *.o md5sum.exe

md5sum.exe: $(OBJECTS)
	$(CC) $(LDFLAGS) -o $@ $(OBJECTS) $(LIBS)

.c.o:
	$(CC) $(CFLAGS) -o $@ -c $<
